### ISSUE TITLE
Semantic versioning note

### ISSUE THREAD

**Issue by ghost** [awsdocs/aws-serverlessrepo-developer-guide#4]
Hello Team,

Just wanted to mention that if we had a note that indicated that:

"
Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version
"
in regards to our semantic versioning. I found this site which discusses it a bit more: https://semver.org/#spec-item-3

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
