### ISSUE TITLE
	The AWS Serverless Repo does not have read access to bucket

### ISSUE THREAD

**Issue by abhijithkumar123** [awsdocs/aws-serverlessrepo-developer-guide#5]
I followed [this tutorial](https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-serverlessrepo-auto-publish.html) and created a pipeline. I'm facing an issue in the publish stage of the pipeline. I see the following error:

An error occurred (BadRequestException) when calling the CreateApplication operation: The AWS Serverless Application Repository does not have read access to bucket '<pipeline-name>', key '<artifact-key>'.Please update your Amazon S3 bucket policy to grant the service read permissions to the application artifacts you have uploaded to your S3 bucket. See the service documentation for more details.

This error won't go away despite me adding the following policy to s3 bucket (as mentioned in the article [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html) )

{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Service": "serverlessrepo.amazonaws.com"
},
"Action": "s3:GetObject",
"Resource": "arn:aws:s3:::<your-bucket-name>/*"
}
]
}

I'm breaking my head over this issue but unable to figure out where I'm going wrong. Please help. Thanks.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
